[Blocked By #15] 회원가입 구현
tjsry0466/hairshop-server pull request #17
Opened 2022-09-23 16:37 UTC by tjsry0466

[#Blocked By #15]
## 개요

- 회원가입 구현

## 상세

- 회원가입을 구현합니다.
- 회원가입시 가입된 유저, accessToken, refreshToken을 반환합니다.
- 이미 가입된 이메일인 경우 400에러를 반환합니다.
- user.entity의 password를 required로 변경합니다.

## 결과

- N/A

### Author 테스트 여부

- [ ] 테스트 제외
- [X] Local 테스트 완료
- [ ] Develop 테스트 완료

### 테스트 방법

- https://dev-hairshop.kyojs.com/graphql

### 체크리스트

- 회원가입 요청시 정상적으로 user와 accessToken, refreshToken이 반환되는지 확인합니다.
- 이미 존재하는 이메일로 회원가입 요청시 400에러가 발생하는지 확인합니다.

2022-09-24 01:44 UTC, SlimskiTheWise requested changes

2022-09-24 01:44 UTC, SlimskiTheWise commented on src/common/error-messages.ts
> +  static readonly alreadyExistsEmailErrorMessage = "이미 회원으로 등록된 이메일입니다.";
문법상 부자연스러운거 같아서 EmailAlreadyExistsErrorMessage 나 duplicateEmailErrorMessage 는 어떨까요?

2022-09-24 01:44 UTC, SlimskiTheWise commented on src/user/interface/add-user.interface.ts
> +export interface IAddUser {
IAddUser 라는 이름이 무엇을 뜻하는지 물어보고 싶습니다!

2022-09-24 01:44 UTC, SlimskiTheWise commented on src/auth/auth.service.ts
> +  }
커밋 메세지는 회원가입 구현인데 login validation 이 포함되어있어 문맥에 맞지 않은거 같습니다. 커밋 문맥에 맞지않으면 더 효과적으로 코드 리뷰를 하기위해 다른 이슈로 분리해서 작업하는게 좋을거 같습니다

2022-09-24 01:51 UTC, SlimskiTheWise requested changes

2022-09-24 01:51 UTC, SlimskiTheWise commented on src/migration/1663949340159-updateUserPasswordRequired.ts
> +  public async up(queryRunner: QueryRunner): Promise<void> {
up, down 이 어떤 의미를 하나요?

2022-09-24 06:12 UTC, tjsry0466 commented on src/migration/1663949340159-updateUserPasswordRequired.ts
> +  public async up(queryRunner: QueryRunner): Promise<void> {
migration시에 적용, 롤백을 의미합니다

2022-09-24 06:12 UTC, tjsry0466 commented on src/user/interface/add-user.interface.ts
> +export interface IAddUser {
I는 인터페이스에 붙이는 prefix입니다

2022-09-24 06:13 UTC, tjsry0466 commented on src/common/error-messages.ts
> +  static readonly alreadyExistsEmailErrorMessage = "이미 회원으로 등록된 이메일입니다.";
넵 전자가 좋아보이네요 변경하겠습니다 ~

2022-09-24 06:14 UTC, tjsry0466 commented on src/auth/auth.service.ts
> +  }
그러네요 잘못 포함된 부분인 것 같네요 해당 부분은 제거하겠습니다

2022-09-24 07:56 UTC, SlimskiTheWise approved these changes

2022-09-25 06:33 UTC, SlimskiTheWise approved these changes

2022-09-25 07:04 UTC, merged